/**
 * The review protocol: generated from the stages (questions, concepts, search strings, method sections),
 * the checks before it is locked, and the integrity checks after locking.
 * @module domain/protocol
 */
import { AI_STEPS, aiMode } from "./ai-steps.js";
import * as frontmatter from "./frontmatter.js";
import { buildQuery } from "./queries.js";
import { chars, comparePy, strip } from "./pytext.js";
import { isLocked, PROTOCOL_SECTIONS, sameValue, STAGE } from "./stages.js";
import { DEFAULT_TA_REASONS } from "./vocabulary.js";

export const PROTOCOL_FILE = "05 - Protocol.md";
export const frozenProtocolName = day => `06 - Protocol (registered ${day}).md`;

const titleWithoutNumber = key => STAGE[key].title.split(" · ")[1];
const sectionsBy = (st, by) => PROTOCOL_SECTIONS.filter(([key]) => ((st.protocol_meta ?? {})[key] ?? {}).by === by).map(([, title]) => title);

/**
 * The protocol note.
 * @param {object} p
 * @param {string} p.reviewName @param {string} p.reviewLink @param {object} p.st review state
 * @param {readonly string[]} p.ftReasons full-text exclusion reasons (screening guide)
 * @param {string} [p.frozen] date of registration, for the frozen copy
 * @param {string} p.generatedBy written to `generated-by`
 */
export function protocolMarkdown({ reviewName, reviewLink, st, ftReasons, frozen = "", generatedBy }) {
  const q = st.questions, t = st.protocol_text;
  const reg = frozen ? "" : st.protocol.locked ?? "";
  const status = frozen ? "registered" : reg ? "current" : "draft";
  const lines = [
    frontmatter.serialize({ type: "review-protocol", review: reviewLink, status, registered: frozen || reg, "generated-by": generatedBy }),
    `# ${reviewName} — protocol` + (frozen ? ` (registered ${frozen})` : reg ? " (current version, incl. amendments)" : " (draft)") + "\n",
  ];
  if (reg) {
    lines.push(`> [!info] Working copy, regenerated by the review tool. The registered version is frozen in ` +
      `[[${chars(st.protocol.file ?? "").slice(0, -3).join("")}]]; amendments since then are listed in [[00 - Review timeline]].\n`);
  } else if (!frozen) lines.push("> [!info] Generated from the review tool — edit the sections in the tool, not here.\n");
  lines.push("## Objectives and review questions (PRISMA-ScR 4)\n",
    `- **Population:** ${q.population || "—"}`, `- **Concept:** ${q.concept || "—"}`,
    `- **Context:** ${q.context || "—"}`, "", `**Main question.** ${q.main || "—"}\n`,
    ...q.sub.map(s => `- ${s}`));
  const drafted = sectionsBy(st, "claude"), approved = sectionsBy(st, "approved");
  for (const [key, title] of PROTOCOL_SECTIONS) {
    lines.push("", `## ${title}\n`, t[key] || "_(to be written)_");
    if (key === "eligibility") lines.push("", "Exclusion reasons used in screening:", ...ftReasons.map(r => `- ${r}`));
    if (key === "sources") lines.push("", "Databases: " + st.queries.databases.join(", "));
    if (key === "charting") lines.push("", "Data items (PRISMA-ScR 11):", ...st.charting.fields.map(f => `- \`${f.name}\` — ${f.description}`));
  }
  lines.push("", "## Search strategy (PRISMA-ScR 8)\n", "| Concept | Role | Terms |", "|---|---|---|",
    ...st.concepts.map(c => `| ${c.name} | ${c.role ?? "AND"} | ${(c.terms ?? []).join("; ")} |`));
  for (const db of st.queries.databases) lines.push("", `**${db}**`, "", "```", buildQuery(st, db) || "(no concepts yet)", "```");
  const aiUsed = Object.entries(AI_STEPS).filter(([k]) => aiMode(st, k) !== "off")
    .map(([k, def]) => [k, def.modes.find(([m]) => m === aiMode(st, k))]);
  if (drafted.length || approved.length || aiUsed.length) {
    lines.push("", "## Use of AI assistance\n", ...aiUsed.map(([k, [, label, desc]]) => `- **${titleWithoutNumber(k)}:** ${label}. ${desc}`));
    for (const [stage, r] of Object.entries(st.reviewer_ai ?? {})) {
      lines.push(`- Second reviewer (${stage === "ta" ? "title/abstract" : "full text"}): ${r.model}, ${chars(r.when).slice(0, 10).join("")}, sheet \`${r.sheet}\`.`);
    }
    if (aiUsed.length && (drafted.length || approved.length)) lines.push("");
    if (approved.length) lines.push("Drafted with an AI assistant (Claude) from the reviewer's decisions, then read and approved by the reviewer: " + approved.join("; ") + ".");
    if (drafted.length) lines.push((approved.length ? "\n" : "") + "Drafted with an AI assistant (Claude) and not yet reviewed: " + drafted.join("; ") + ".");
  }
  if (st.pilots.length) {
    lines.push("", "## Search validation\n", "| Date | Database | Hits | Test set retrieved |", "|---|---|---:|---:|",
      ...st.pilots.map(p => `| ${chars(p.when).slice(0, 10).join("")} | ${p.database} | ${p.hits} | ${p.retrieved}/${p.test_set} |`));
  }
  return lines.join("\n") + "\n";
}

/**
 * What must be in order before the protocol is locked.
 * @returns {{label: string, ok: boolean, detail: string, required: boolean}[]}
 */
export function lockChecks(st, reasons) {
  const t = st.protocol_text;
  const empty = PROTOCOL_SECTIONS.filter(([key]) => !strip(t[key] || "")).map(([, title]) => title);
  const holders = [...new Set(Object.values(t).flatMap(v => [...String(v || "").matchAll(/\[[^\]\n]{2,40}\]/g)].map(m => m[0])))].sort(comparePy);
  const drafted = sectionsBy(st, "claude");
  const pilot = st.stages.pilot.status;
  const checked = st.pilots.filter(p => p.test_set !== "" && p.test_set !== null && p.test_set !== undefined);
  const sup = st.supervisor_review ?? {};
  const row = (label, ok, detail, required) => ({ label, ok: Boolean(ok), detail, required });
  return [
    row("Review questions written", st.questions.main, chars(st.questions.main).slice(0, 80).join("") || "stage 1", true),
    row("Concept table and search strings", st.concepts.length, `${st.concepts.length} concept block(s)`, true),
    row("All protocol sections written", !empty.length, empty.length ? "missing: " + empty.join(", ") : "8 of 8", true),
    row("No placeholders left", !holders.length, holders.length ? "replace: " + holders.join(", ") : "none found", true),
    row("Exclusion reasons set", !sameValue([...reasons.ta], [...DEFAULT_TA_REASONS]), `${reasons.ft.length} full-text reasons`, true),
    row("Search piloted and checked against the test set", pilot === "skipped" || checked.length,
      pilot === "skipped" ? "skipped: " + st.stages.pilot.reason
        : checked.length ? `last check ${checked.at(-1).retrieved}/${checked.at(-1).test_set}` : "no checked pilot", true),
    row("Reviewed by your supervisor", sup.by, sup.by ? `${sup.by}, ${sup.when}` : "not yet", true),
    row("Sections drafted by Claude were read by you", !drafted.length,
      drafted.length ? "still unread drafts: " + drafted.join(", ") : "all edited or approved by you", false),
  ];
}

/**
 * Changes after locking that bypassed the amendment log.
 * @param {object} st @param {{ta: readonly string[], ft: readonly string[]}} reasons current screening guide
 * @param {string|null} frozenHash SHA-256 (hex) of the registered protocol file now, null if it is missing
 */
export function integrityProblems(st, reasons, frozenHash) {
  const out = [];
  const snap = st.protocol.snapshot ?? {};
  if (!isLocked(st) || !Object.keys(snap).length) return out;
  const changed = !sameValue([...reasons.ta], snap.ta_reasons) || !sameValue([...reasons.ft], snap.ft_reasons);
  if (changed && !st.amendments.some(a => a.what === "criteria")) out.push("exclusion reasons in the Screening guide changed after locking without a logged amendment");
  if (frozenHash !== null && frozenHash !== st.protocol.sha256) out.push(`the registered protocol file '${st.protocol.file}' was edited after locking`);
  return out;
}
