/**
 * Readable notes written from the review state: the timeline, the search strategy, the PRISMA-ScR
 * checklist, the charting table (12 - Charting.base) and the exports for writing (charting CSV, BibTeX).
 * @module domain/stage-notes
 */
import { writeRows } from "./csv.js";
import * as frontmatter from "./frontmatter.js";
import { buildQuery } from "./queries.js";
import { chars } from "./pytext.js";
import { CHECKLIST, isLocked, STAGE, STAGES, STATUS_ICON } from "./stages.js";

export const STAGE_FILES = Object.freeze({
  timeline: "00 - Review timeline.md",
  strategy: "03 - Search strategy.md",
  checklist: "14 - PRISMA-ScR checklist.md",
  chartingBase: "12 - Charting.base",
});

const withoutMd = name => chars(name).slice(0, -3).join("");

/** 00 - Review timeline.md: stages, protocol, amendments, idea log and every event (newest first). */
export function timelineNote({ reviewName, reviewLink, st, today }) {
  const lines = [frontmatter.serialize({ type: "review-timeline", review: reviewLink, generated: today }),
    `# ${reviewName} — timeline\n`,
    "> [!info] Generated by Review Studio. Links: [[03 - Search strategy]] · [[05 - Protocol]] · [[08 - Screening.base]] · [[14 - PRISMA flow]] · [[14 - PRISMA-ScR checklist]]\n",
    "## Stages\n", "| Stage | Optional | Status | Updated | Skip reason |", "|---|:-:|---|---|---|"];
  for (const { key, title, optional } of STAGES) {
    const s = st.stages[key];
    lines.push(`| ${title} | ${optional ? "yes" : ""} | ${STATUS_ICON[s.status]} ${s.status} | ${s.updated} | ${s.reason} |`);
  }
  const p = st.protocol;
  lines.push("", "## Protocol\n", `- Locked: ${p.locked || "no"}` + (p.file ? ` — [[${withoutMd(p.file)}]]` : ""),
    `- Registration: ${p.registration || "—"}`, `- Git commit: ${p.commit || "—"}`, "",
    "## Amendments after locking\n", "| When | What | Reason |", "|---|---|---|",
    ...(st.amendments.length ? st.amendments.map(a => `| ${a.when} | ${a.what} | ${a.reason} |`) : ["| — | | |"]));
  if (st.idea.length) lines.push("", "## Idea log\n", ...st.idea.map(i => `- **${i.when}** — ${i.text}`));
  lines.push("", "## Events\n", "| When | Stage | What |", "|---|---|---|",
    ...[...st.events].reverse().map(e => `| ${e.when} | ${STAGE[e.stage]?.title ?? e.stage} | ${String(e.text).replaceAll("|", "/")} |`));
  return lines.join("\n") + "\n";
}

/**
 * 03 - Search strategy.md: questions, concept table, search strings and pilot runs; null while there is
 * nothing to show (no concepts yet and no earlier note).
 */
export function strategyNote({ reviewName, reviewLink, st, today, exists }) {
  if (!st.concepts.length && !exists) return null;
  const q = st.questions;
  const lines = [frontmatter.serialize({ type: "search-strategy", review: reviewLink, generated: today }),
    `# ${reviewName} — search strategy\n`, "> [!info] Generated by the review tool.\n",
    "## Review questions\n", `- **Population:** ${q.population || "—"}`, `- **Concept:** ${q.concept || "—"}`,
    `- **Context:** ${q.context || "—"}`, "", `**Main question.** ${q.main || "—"}\n`, ...q.sub.map(s => `- ${s}`)];
  if (q.history.length) {
    lines.push("", "<details><summary>Earlier versions</summary>\n",
      ...[...q.history].reverse().map(h => `- **${h.when}** (${h.why || "no reason given"}): ${h.main || "—"}`), "\n</details>");
  }
  lines.push("", "## Concept table\n", "| Concept | Role | Terms |", "|---|---|---|",
    ...st.concepts.map(c => `| ${c.name} | ${c.role ?? "AND"} | ${(c.terms ?? []).join("; ")} |`), "", "## Search strings\n");
  for (const db of st.queries.databases) {
    lines.push(`**${db}**${st.queries.manual[db] ? " (edited by hand)" : ""}`, "", "```", buildQuery(st, db) || "(no concepts yet)", "```", "");
  }
  lines.push("## Pilot runs\n", "| When | Database | Hits | Test set retrieved | Note |", "|---|---|---:|---:|---|",
    ...(st.pilots.length ? st.pilots.map(p => `| ${p.when} | ${p.database} | ${p.hits} | ${p.retrieved}/${p.test_set} | ${p.note} |`) : ["| — | | | | |"]));
  const last = [...st.pilots].reverse().find(p => p.missed?.length);
  if (last) lines.push("", `<details><summary>Test-set papers missed by the last pilot (${last.when})</summary>\n`, ...last.missed.map(m => `- ${m}`), "\n</details>");
  return lines.join("\n") + "\n";
}

/**
 * Evidence the tool can see for each PRISMA-ScR item ("" = only the reviewer can judge).
 * @param {object} p @param {object} p.st @param {import("./flow.js").SearchRow[]} p.searches
 * @param {import("./frontmatter.js").Properties[]} p.records @param {boolean} p.guideExists @param {boolean} p.flowExists
 * @returns {Record<number, string>}
 */
export function checklistEvidence({ st, searches, records, guideExists, flowExists }) {
  const s = st.stages;
  const databases = searches.filter(r => r.kind === "database").length;
  return {
    4: st.questions.main ? "questions written" : "",
    5: isLocked(st) ? `registered ${st.protocol.locked}` : s.registration.status === "skipped" ? "registration skipped: " + s.registration.reason : "",
    6: guideExists ? "exclusion reasons defined" : "",
    7: searches.length ? `${databases} database search${databases === 1 ? "" : "es"} logged` : "",
    8: databases ? "full strings in Search strategy" : "",
    9: records.some(r => r.ta_decision !== "pending") ? "screening decisions recorded" : "",
    11: `${st.charting.fields.length} data items defined`,
    12: s.appraisal.status === "skipped" ? "skipped: " + s.appraisal.reason : s.appraisal.status !== "not-started" ? "appraisal recorded" : "",
    14: flowExists && searches.length ? "PRISMA flow generated" : "",
    15: s.charting.status !== "not-started" ? "charting table" : "",
    16: s.appraisal.status === "skipped" ? "not performed (skipped)" : "",
  };
}

/** 14 - PRISMA-ScR checklist.md */
export function checklistNote({ reviewName, reviewLink, st, today, evidence }) {
  const lines = [frontmatter.serialize({ type: "prisma-checklist", review: reviewLink, generated: today }),
    `# ${reviewName} — PRISMA-ScR checklist\n`,
    "> [!info] Generated by the review tool. Tick items and give their location in the manuscript in the tool. Check the official checklist (Tricco et al. 2018) before submitting.\n",
    "| # | Item | Reported? | Location | Evidence in the vault |", "|---:|---|:-:|---|---|"];
  for (const [n, item, desc] of CHECKLIST) {
    const c = st.checklist[String(n)] ?? {};
    lines.push(`| ${n} | **${item}** — ${desc} | ${c.done ? "✔" : ""} | ${c.location ?? ""} | ${evidence[n] ?? ""} |`);
  }
  return lines.join("\n") + "\n";
}

/** 12 - Charting.base: the charting form as a table over the included records (and appraisal, if used). */
export function chartingBase(st, recordsPath, withAppraisal) {
  const views = [["Charting", ["file.name", "year", ...st.charting.fields.map(f => `chart_${f.name}`)]]];
  if (withAppraisal) views.push(["Appraisal", ["file.name", "year", "chart_study_type", "appraisal", "appraisal_note"]]);
  return "views:\n" + views.map(([name, order]) =>
    `  - type: table\n    name: ${name}\n    filters:\n      and:\n        - file.inFolder("${recordsPath}")\n        - ft_decision == "include"\n    order:\n`
    + order.map(c => `      - ${c}\n`).join("")
    + "    sort:\n      - property: file.name\n        direction: ASC\n    columnSize:\n      file.name: 380\n").join("");
}

/** Charting and appraisal of the included records as CSV (with a BOM, for Excel). */
export function chartingCsv(st, includedProps) {
  const keys = [...st.charting.fields.map(f => `chart_${f.name}`), "appraisal", "appraisal_note"];
  const rows = includedProps.map(f => [f.record_id, f.authors, f.year, f.title, f.journal, f.doi, ...keys.map(k => f[k] ?? "")]);
  return "﻿" + writeRows([["record_id", "authors", "year", "title", "journal", "doi", ...keys], ...rows]);
}

/** The included records as BibTeX (@article entries keyed Surname + year + record id). */
export function bibtex(includedProps) {
  return includedProps.map(f => {
    const authors = String(f.authors ?? "");
    const first = authors ? ((authors.split(";")[0] || "anon").split(",")[0].trim().split(/\s+/).at(-1) ?? "") : "anon";
    const key = `${first}${f.year}${f.record_id}`.replace(/[^\p{L}\p{N}_]/gu, "");
    const fields = { title: f.title, author: authors.split(";").map(a => a.trim()).filter(Boolean).join(" and "), year: f.year, journal: f.journal, doi: f.doi };
    return `@article{${key},\n` + Object.entries(fields).filter(([, v]) => v).map(([k, v]) => `  ${k} = {${v}}`).join(",\n") + "\n}\n";
  }).join("\n");
}
